module Vers
  module Models
    type commit_tag_delete_params =
      { tag_name: String } & Vers::Internal::Type::request_parameters

    class CommitTagDeleteParams < Vers::Internal::Type::BaseModel
      extend Vers::Internal::Type::RequestParameters::Converter
      include Vers::Internal::Type::RequestParameters

      attr_accessor tag_name: String

      def initialize: (
        tag_name: String,
        ?request_options: Vers::request_opts
      ) -> void

      def to_hash: -> {
        tag_name: String,
        request_options: Vers::RequestOptions
      }
    end
  end
end
