module Vers
  module Models
    type create_tag_request =
      { commit_id: String, tag_name: String, description: String? }

    class CreateTagRequest < Vers::Internal::Type::BaseModel
      attr_accessor commit_id: String

      attr_accessor tag_name: String

      attr_accessor description: String?

      def initialize: (
        commit_id: String,
        tag_name: String,
        ?description: String?
      ) -> void

      def to_hash: -> {
        commit_id: String,
        tag_name: String,
        description: String?
      }
    end
  end
end
