module Vers
  module Models
    type repository_fork_params =
      {  } & Vers::Internal::Type::request_parameters

    class RepositoryForkParams < Vers::Models::ForkRepositoryRequest
      extend Vers::Internal::Type::RequestParameters::Converter
      include Vers::Internal::Type::RequestParameters

      def initialize: (?request_options: Vers::request_opts) -> void

      def to_hash: -> { request_options: Vers::RequestOptions }
    end
  end
end
