module Vers
  module Models
    type repository_set_visibility_params =
      { repo_name: String } & Vers::Internal::Type::request_parameters

    class RepositorySetVisibilityParams < Vers::Models::SetRepositoryVisibilityRequest
      extend Vers::Internal::Type::RequestParameters::Converter
      include Vers::Internal::Type::RequestParameters

      def repo_name: -> String

      def repo_name=: (String _) -> String

      def initialize: (
        repo_name: String,
        ?request_options: Vers::request_opts
      ) -> void

      def to_hash: -> {
        repo_name: String,
        request_options: Vers::RequestOptions
      }
    end
  end
end
