module Vers
  module Models
    type vm_branch_by_tag_params =
      { tag_name: String, count: Integer }
      & Vers::Internal::Type::request_parameters

    class VmBranchByTagParams < Vers::Internal::Type::BaseModel
      extend Vers::Internal::Type::RequestParameters::Converter
      include Vers::Internal::Type::RequestParameters

      attr_accessor tag_name: String

      attr_reader count: Integer?

      def count=: (Integer) -> Integer

      def initialize: (
        tag_name: String,
        ?count: Integer,
        ?request_options: Vers::request_opts
      ) -> void

      def to_hash: -> {
        tag_name: String,
        count: Integer,
        request_options: Vers::RequestOptions
      }
    end
  end
end
