module Vers
  module Models
    type vm_branch_by_vm_response = { vms: ::Array[Vers::NewVmResponse] }

    class VmBranchByVmResponse < Vers::Internal::Type::BaseModel
      attr_accessor vms: ::Array[Vers::NewVmResponse]

      def initialize: (vms: ::Array[Vers::NewVmResponse]) -> void

      def to_hash: -> { vms: ::Array[Vers::NewVmResponse] }
    end
  end
end
