module Vers
  module Models
    type vm_commit_response = { commit_id: String }

    class VmCommitResponse < Vers::Internal::Type::BaseModel
      attr_accessor commit_id: String

      def initialize: (commit_id: String) -> void

      def to_hash: -> { commit_id: String }
    end
  end
end
