module Vers
  module Models
    type vm_commit_params =
      { keep_paused: bool, skip_wait_boot: bool }
      & Vers::Internal::Type::request_parameters

    class VmCommitParams < Vers::Internal::Type::BaseModel
      extend Vers::Internal::Type::RequestParameters::Converter
      include Vers::Internal::Type::RequestParameters

      attr_reader keep_paused: bool?

      def keep_paused=: (bool) -> bool

      attr_reader skip_wait_boot: bool?

      def skip_wait_boot=: (bool) -> bool

      def initialize: (
        ?keep_paused: bool,
        ?skip_wait_boot: bool,
        ?request_options: Vers::request_opts
      ) -> void

      def to_hash: -> {
        keep_paused: bool,
        skip_wait_boot: bool,
        request_options: Vers::RequestOptions
      }
    end
  end
end
