module Vers
  module Models
    type vm_commit_params =
      {
        vm_id: String,
        keep_paused: bool,
        skip_wait_boot: bool,
        commit_id: String?,
        description: String?,
        name: String?
      }
      & Vers::Internal::Type::request_parameters

    class VmCommitParams < Vers::Internal::Type::BaseModel
      extend Vers::Internal::Type::RequestParameters::Converter
      include Vers::Internal::Type::RequestParameters

      attr_accessor vm_id: String

      attr_reader keep_paused: bool?

      def keep_paused=: (bool) -> bool

      attr_reader skip_wait_boot: bool?

      def skip_wait_boot=: (bool) -> bool

      attr_accessor commit_id: String?

      attr_accessor description: String?

      attr_accessor name: String?

      def initialize: (
        vm_id: String,
        ?keep_paused: bool,
        ?skip_wait_boot: bool,
        ?commit_id: String?,
        ?description: String?,
        ?name: String?,
        ?request_options: Vers::request_opts
      ) -> void

      def to_hash: -> {
        vm_id: String,
        keep_paused: bool,
        skip_wait_boot: bool,
        commit_id: String?,
        description: String?,
        name: String?,
        request_options: Vers::RequestOptions
      }
    end
  end
end
