module Vers
  module Models
    type vm_delete_response = { vm_id: String }

    class VmDeleteResponse < Vers::Internal::Type::BaseModel
      attr_accessor vm_id: String

      def initialize: (vm_id: String) -> void

      def to_hash: -> { vm_id: String }
    end
  end
end
