module Vers
  module Models
    type vm_delete_response = { deleted_ids: ::Array[String] }

    class VmDeleteResponse < Vers::Internal::Type::BaseModel
      attr_accessor deleted_ids: ::Array[String]

      def initialize: (deleted_ids: ::Array[String]) -> void

      def to_hash: -> { deleted_ids: ::Array[String] }
    end
  end
end
