module Vers
  module Models
    type vm_delete_params =
      { skip_wait_boot: bool } & Vers::Internal::Type::request_parameters

    class VmDeleteParams < Vers::Internal::Type::BaseModel
      extend Vers::Internal::Type::RequestParameters::Converter
      include Vers::Internal::Type::RequestParameters

      attr_reader skip_wait_boot: bool?

      def skip_wait_boot=: (bool) -> bool

      def initialize: (
        ?skip_wait_boot: bool,
        ?request_options: Vers::request_opts
      ) -> void

      def to_hash: -> {
        skip_wait_boot: bool,
        request_options: Vers::RequestOptions
      }
    end
  end
end
