module Vers
  module Models
    type vm_get_ssh_key_params =
      { vm_id: String } & Vers::Internal::Type::request_parameters

    class VmGetSSHKeyParams < Vers::Internal::Type::BaseModel
      extend Vers::Internal::Type::RequestParameters::Converter
      include Vers::Internal::Type::RequestParameters

      attr_accessor vm_id: String

      def initialize: (
        vm_id: String,
        ?request_options: Vers::request_opts
      ) -> void

      def to_hash: -> { vm_id: String, request_options: Vers::RequestOptions }
    end
  end
end
