module FirecrackerManager
  module Resources
    class API
      attr_reader cluster: FirecrackerManager::Resources::API::Cluster

      attr_reader vm: FirecrackerManager::Resources::API::Vm

      attr_reader rootfs: FirecrackerManager::Resources::API::Rootfs

      attr_reader health: FirecrackerManager::Resources::API::Health

      attr_reader telemetry: FirecrackerManager::Resources::API::Telemetry

      def initialize: (client: FirecrackerManager::Client) -> void
    end
  end
end
