module FirecrackerManager
  module Models
    module API
      type rootf_upload_params =
        { dockerfile: String }
        & FirecrackerManager::Internal::Type::request_parameters

      class RootfUploadParams < FirecrackerManager::Internal::Type::BaseModel
        extend FirecrackerManager::Internal::Type::RequestParameters::Converter
        include FirecrackerManager::Internal::Type::RequestParameters

        attr_reader dockerfile: String?

        def dockerfile=: (String) -> String

        def initialize: (
          ?dockerfile: String,
          ?request_options: FirecrackerManager::request_opts
        ) -> void

        def to_hash: -> {
          dockerfile: String,
          request_options: FirecrackerManager::RequestOptions
        }
      end
    end
  end
end
