module FirecrackerManager
  module Models
    module API
      type vm_delete_params =
        { recursive: bool }
        & FirecrackerManager::Internal::Type::request_parameters

      class VmDeleteParams < FirecrackerManager::Internal::Type::BaseModel
        extend FirecrackerManager::Internal::Type::RequestParameters::Converter
        include FirecrackerManager::Internal::Type::RequestParameters

        attr_accessor recursive: bool

        def initialize: (
          recursive: bool,
          ?request_options: FirecrackerManager::request_opts
        ) -> void

        def to_hash: -> {
          recursive: bool,
          request_options: FirecrackerManager::RequestOptions
        }
      end
    end
  end
end
