module FirecrackerManager
  module Resources
    class API
      class Health
        def check: (
          ?request_options: FirecrackerManager::request_opts
        ) -> String

        def initialize: (client: FirecrackerManager::Client) -> void
      end
    end
  end
end
