module FirecrackerManager
  module Resources
    class API
      class Rootfs
        def list: (
          ?request_options: FirecrackerManager::request_opts
        ) -> FirecrackerManager::Models::API::RootfListResponse

        def delete: (
          String rootfs_id,
          ?request_options: FirecrackerManager::request_opts
        ) -> FirecrackerManager::Models::API::RootfDeleteResponse

        def upload: (
          String rootfs_id,
          ?dockerfile: String,
          ?request_options: FirecrackerManager::request_opts
        ) -> FirecrackerManager::Models::API::RootfUploadResponse

        def initialize: (client: FirecrackerManager::Client) -> void
      end
    end
  end
end
