module FirecrackerManager
  module Resources
    class API
      class Telemetry
        def get_info: (
          ?request_options: FirecrackerManager::request_opts
        ) -> FirecrackerManager::API::TelemetryDto

        def initialize: (client: FirecrackerManager::Client) -> void
      end
    end
  end
end
