module Vers
  module Resources
    class Orchestrator
      class Node
        def list_vms: (
          String node_id,
          ?request_options: Vers::request_opts
        ) -> Vers::Orchestrator::VmListAllResponse

        def initialize: (client: Vers::Client) -> void
      end
    end
  end
end
