# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) &&
   caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "firecracker_manager/version"
require_relative "firecracker_manager/internal/util"
require_relative "firecracker_manager/internal/type/converter"
require_relative "firecracker_manager/internal/type/unknown"
require_relative "firecracker_manager/internal/type/boolean"
require_relative "firecracker_manager/internal/type/file_input"
require_relative "firecracker_manager/internal/type/enum"
require_relative "firecracker_manager/internal/type/union"
require_relative "firecracker_manager/internal/type/array_of"
require_relative "firecracker_manager/internal/type/hash_of"
require_relative "firecracker_manager/internal/type/base_model"
require_relative "firecracker_manager/internal/type/base_page"
require_relative "firecracker_manager/internal/type/request_parameters"
require_relative "firecracker_manager/internal"
require_relative "firecracker_manager/request_options"
require_relative "firecracker_manager/file_part"
require_relative "firecracker_manager/errors"
require_relative "firecracker_manager/internal/transport/base_client"
require_relative "firecracker_manager/internal/transport/pooled_net_requester"
require_relative "firecracker_manager/client"
require_relative "firecracker_manager/models/api/cluster_create_params"
require_relative "firecracker_manager/models/api/cluster_patch_params"
require_relative "firecracker_manager/models/api/vm_branch_params"
require_relative "firecracker_manager/models/api/vm_commit_request"
require_relative "firecracker_manager/models/api/vm_patch_params"
require_relative "firecracker_manager/models/api/cluster_create_params"
require_relative "firecracker_manager/models/api/cluster_create_response"
require_relative "firecracker_manager/models/api/cluster_delete_params"
require_relative "firecracker_manager/models/api/cluster_delete_response"
require_relative "firecracker_manager/models/api/cluster_delete_response"
require_relative "firecracker_manager/models/api/cluster_dto"
require_relative "firecracker_manager/models/api/cluster_get_ssh_key_params"
require_relative "firecracker_manager/models/api/cluster_get_ssh_key_response"
require_relative "firecracker_manager/models/api/cluster_list_params"
require_relative "firecracker_manager/models/api/cluster_list_response"
require_relative "firecracker_manager/models/api/cluster_retrieve_params"
require_relative "firecracker_manager/models/api/cluster_retrieve_response"
require_relative "firecracker_manager/models/api/cluster_update_params"
require_relative "firecracker_manager/models/api/cluster_update_response"
require_relative "firecracker_manager/models/api/health_check_params"
require_relative "firecracker_manager/models/api/health_check_response"
require_relative "firecracker_manager/models/api/rootf_delete_params"
require_relative "firecracker_manager/models/api/rootf_delete_response"
require_relative "firecracker_manager/models/api/rootf_list_params"
require_relative "firecracker_manager/models/api/rootf_list_response"
require_relative "firecracker_manager/models/api/rootfs_delete_response"
require_relative "firecracker_manager/models/api/rootfs_list_response"
require_relative "firecracker_manager/models/api/rootfs_upload_response"
require_relative "firecracker_manager/models/api/rootf_upload_params"
require_relative "firecracker_manager/models/api/rootf_upload_response"
require_relative "firecracker_manager/models/api/telemetry_dto"
require_relative "firecracker_manager/models/api/telemetry_get_info_params"
require_relative "firecracker_manager/models/api/vm_branch_params"
require_relative "firecracker_manager/models/api/vm_branch_response"
require_relative "firecracker_manager/models/api/vm_commit_params"
require_relative "firecracker_manager/models/api/vm_commit_response"
require_relative "firecracker_manager/models/api/vm_commit_response"
require_relative "firecracker_manager/models/api/vm_delete_params"
require_relative "firecracker_manager/models/api/vm_delete_response"
require_relative "firecracker_manager/models/api/vm_delete_response"
require_relative "firecracker_manager/models/api/vm_dto"
require_relative "firecracker_manager/models/api/vm_get_ssh_key_params"
require_relative "firecracker_manager/models/api/vm_get_ssh_key_response"
require_relative "firecracker_manager/models/api/vm_list_params"
require_relative "firecracker_manager/models/api/vm_list_response"
require_relative "firecracker_manager/models/api/vm_retrieve_params"
require_relative "firecracker_manager/models/api/vm_retrieve_response"
require_relative "firecracker_manager/models/api/vm_update_params"
require_relative "firecracker_manager/models/api/vm_update_response"
require_relative "firecracker_manager/models"
require_relative "firecracker_manager/resources/api"
require_relative "firecracker_manager/resources/api/cluster"
require_relative "firecracker_manager/resources/api/health"
require_relative "firecracker_manager/resources/api/rootfs"
require_relative "firecracker_manager/resources/api/telemetry"
require_relative "firecracker_manager/resources/api/vm"
