# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "base64"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "openssl"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) &&
   caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "vers/version"
require_relative "vers/internal/util"
require_relative "vers/internal/type/converter"
require_relative "vers/internal/type/unknown"
require_relative "vers/internal/type/boolean"
require_relative "vers/internal/type/file_input"
require_relative "vers/internal/type/enum"
require_relative "vers/internal/type/union"
require_relative "vers/internal/type/array_of"
require_relative "vers/internal/type/hash_of"
require_relative "vers/internal/type/base_model"
require_relative "vers/internal/type/base_page"
require_relative "vers/internal/type/request_parameters"
require_relative "vers/internal"
require_relative "vers/request_options"
require_relative "vers/file_part"
require_relative "vers/errors"
require_relative "vers/internal/transport/base_client"
require_relative "vers/internal/transport/pooled_net_requester"
require_relative "vers/client"
require_relative "vers/models/create_tag_request"
require_relative "vers/models/update_tag_request"
require_relative "vers/models/update_commit_request"
require_relative "vers/models/create_repository_request"
require_relative "vers/models/create_repo_tag_request"
require_relative "vers/models/fork_repository_request"
require_relative "vers/models/set_repository_visibility_request"
require_relative "vers/models/update_repo_tag_request"
require_relative "vers/models/new_root_request"
require_relative "vers/models/vm_resize_disk_request"
require_relative "vers/models/vm_from_commit_request"
require_relative "vers/models/vm_update_state_request"
require_relative "vers/models/commit_delete_params"
require_relative "vers/models/commit_info"
require_relative "vers/models/commit_list_params"
require_relative "vers/models/commit_list_parents_params"
require_relative "vers/models/commit_list_parents_response"
require_relative "vers/models/commit_list_public_params"
require_relative "vers/models/commit_tag_create_params"
require_relative "vers/models/commit_tag_delete_params"
require_relative "vers/models/commit_tag_get_params"
require_relative "vers/models/commit_tag_list_params"
require_relative "vers/models/commit_tag_update_params"
require_relative "vers/models/commit_update_params"
require_relative "vers/models/create_repository_response"
require_relative "vers/models/create_repo_tag_response"
require_relative "vers/models/create_tag_response"
require_relative "vers/models/error_response"
require_relative "vers/models/fork_repository_response"
require_relative "vers/models/list_commits_response"
require_relative "vers/models/list_public_repositories_response"
require_relative "vers/models/list_repositories_response"
require_relative "vers/models/list_repo_tags_response"
require_relative "vers/models/list_tags_response"
require_relative "vers/models/new_vm_response"
require_relative "vers/models/new_vms_response"
require_relative "vers/models/public_repository_get_params"
require_relative "vers/models/public_repository_get_tag_params"
require_relative "vers/models/public_repository_info"
require_relative "vers/models/public_repository_list_params"
require_relative "vers/models/public_repository_list_tags_params"
require_relative "vers/models/repository_create_params"
require_relative "vers/models/repository_create_tag_params"
require_relative "vers/models/repository_delete_params"
require_relative "vers/models/repository_delete_tag_params"
require_relative "vers/models/repository_fork_params"
require_relative "vers/models/repository_get_params"
require_relative "vers/models/repository_get_tag_params"
require_relative "vers/models/repository_info"
require_relative "vers/models/repository_list_params"
require_relative "vers/models/repository_list_tags_params"
require_relative "vers/models/repository_set_visibility_params"
require_relative "vers/models/repository_update_tag_params"
require_relative "vers/models/repo_tag_info"
require_relative "vers/models/tag_info"
require_relative "vers/models/vm"
require_relative "vers/models/vm_branch_by_commit_params"
require_relative "vers/models/vm_branch_by_tag_params"
require_relative "vers/models/vm_branch_by_vm_params"
require_relative "vers/models/vm_branch_params"
require_relative "vers/models/vm_commit_params"
require_relative "vers/models/vm_commit_response"
require_relative "vers/models/vm_create_root_params"
require_relative "vers/models/vm_delete_params"
require_relative "vers/models/vm_delete_response"
require_relative "vers/models/vm_get_metadata_params"
require_relative "vers/models/vm_get_ssh_key_params"
require_relative "vers/models/vm_list_params"
require_relative "vers/models/vm_list_response"
require_relative "vers/models/vm_metadata_response"
require_relative "vers/models/vm_resize_disk_params"
require_relative "vers/models/vm_restore_from_commit_params"
require_relative "vers/models/vm_ssh_key_response"
require_relative "vers/models/vm_status_params"
require_relative "vers/models/vm_update_state_params"
require_relative "vers/models"
require_relative "vers/resources/commits"
require_relative "vers/resources/commit_tags"
require_relative "vers/resources/public_repositories"
require_relative "vers/resources/repositories"
require_relative "vers/resources/vm"
