module Vers
  module Models
    module API
      type telemetry_dto =
        {
          id: String,
          cpu_cores_available: Integer,
          cpu_cores_margin: Integer,
          cpu_cores_total: Integer,
          cpu_cores_used: Integer,
          disk_data_mib_available: Integer,
          disk_data_mib_total: Integer,
          disk_vm_mib_available: Integer,
          disk_vm_mib_total: Integer,
          memory_mib_available: Integer,
          memory_mib_margin: Integer,
          memory_mib_total: Integer,
          memory_mib_used: Integer,
          vm_network_count_in_use: Integer,
          vm_network_count_total: Integer
        }

      class TelemetryDto < Vers::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor cpu_cores_available: Integer

        attr_accessor cpu_cores_margin: Integer

        attr_accessor cpu_cores_total: Integer

        attr_accessor cpu_cores_used: Integer

        attr_accessor disk_data_mib_available: Integer

        attr_accessor disk_data_mib_total: Integer

        attr_accessor disk_vm_mib_available: Integer

        attr_accessor disk_vm_mib_total: Integer

        attr_accessor memory_mib_available: Integer

        attr_accessor memory_mib_margin: Integer

        attr_accessor memory_mib_total: Integer

        attr_accessor memory_mib_used: Integer

        attr_accessor vm_network_count_in_use: Integer

        attr_accessor vm_network_count_total: Integer

        def initialize: (
          id: String,
          cpu_cores_available: Integer,
          cpu_cores_margin: Integer,
          cpu_cores_total: Integer,
          cpu_cores_used: Integer,
          disk_data_mib_available: Integer,
          disk_data_mib_total: Integer,
          disk_vm_mib_available: Integer,
          disk_vm_mib_total: Integer,
          memory_mib_available: Integer,
          memory_mib_margin: Integer,
          memory_mib_total: Integer,
          memory_mib_used: Integer,
          vm_network_count_in_use: Integer,
          vm_network_count_total: Integer
        ) -> void

        def to_hash: -> {
          id: String,
          cpu_cores_available: Integer,
          cpu_cores_margin: Integer,
          cpu_cores_total: Integer,
          cpu_cores_used: Integer,
          disk_data_mib_available: Integer,
          disk_data_mib_total: Integer,
          disk_vm_mib_available: Integer,
          disk_vm_mib_total: Integer,
          memory_mib_available: Integer,
          memory_mib_margin: Integer,
          memory_mib_total: Integer,
          memory_mib_used: Integer,
          vm_network_count_in_use: Integer,
          vm_network_count_total: Integer
        }
      end
    end
  end
end
