module Vers
  module Models
    module API
      type vm_branch_request = { alias_: String? }

      class VmBranchRequest < Vers::Internal::Type::BaseModel
        attr_accessor alias_: String?

        def initialize: (?alias_: String?) -> void

        def to_hash: -> { alias_: String? }
      end
    end
  end
end
