module Vers
  module Models
    module API
      type vm_commit_request = { tags: ::Array[String]? }

      class VmCommitRequest < Vers::Internal::Type::BaseModel
        attr_accessor tags: ::Array[String]?

        def initialize: (?tags: ::Array[String]?) -> void

        def to_hash: -> { tags: ::Array[String]? }
      end
    end
  end
end
