module Vers
  module Models
    module Orchestrator
      type vm_branch_response = { vm_id: String }

      class VmBranchResponse < Vers::Internal::Type::BaseModel
        attr_accessor vm_id: String

        def initialize: (vm_id: String) -> void

        def to_hash: -> { vm_id: String }
      end
    end
  end
end
