module Vers
  module Resources
    class API
      class Cluster
        def create: (
          cluster_create_params: Vers::Models::API::ClusterCreateParams,
          ?request_options: Vers::request_opts
        ) -> Vers::Models::API::ClusterCreateResponse

        def retrieve: (
          String cluster_id_or_alias,
          ?request_options: Vers::request_opts
        ) -> Vers::Models::API::ClusterRetrieveResponse

        def update: (
          String cluster_id_or_alias,
          ?alias_: String?,
          ?request_options: Vers::request_opts
        ) -> Vers::Models::API::ClusterUpdateResponse

        def list: (
          ?request_options: Vers::request_opts
        ) -> Vers::Models::API::ClusterListResponse

        def delete: (
          String cluster_id_or_alias,
          ?request_options: Vers::request_opts
        ) -> Vers::Models::API::ClusterDeleteResponse

        def get_ssh_key: (
          String cluster_id_or_alias,
          ?request_options: Vers::request_opts
        ) -> Vers::Models::API::ClusterGetSSHKeyResponse

        def initialize: (client: Vers::Client) -> void
      end
    end
  end
end
