module Vers
  class Client < Vers::Internal::Transport::BaseClient
    DEFAULT_MAX_RETRIES: 2

    DEFAULT_TIMEOUT_IN_SECONDS: Float

    DEFAULT_INITIAL_RETRY_DELAY: Float

    DEFAULT_MAX_RETRY_DELAY: Float

    attr_reader api_key: String?

    attr_reader vm: Vers::Resources::Vm

    attr_reader commits: Vers::Resources::Commits

    attr_reader commit_tags: Vers::Resources::CommitTags

    attr_reader repositories: Vers::Resources::Repositories

    attr_reader public_repositories: Vers::Resources::PublicRepositories

    private def auth_headers: -> ::Hash[String, String]

    def initialize: (
      ?api_key: String?,
      ?base_url: String?,
      ?max_retries: Integer,
      ?timeout: Float,
      ?initial_retry_delay: Float,
      ?max_retry_delay: Float
    ) -> void
  end
end
