module Vers
  class ErrorResponse = Vers::Models::ErrorResponse

  class NewRootRequest = Vers::Models::NewRootRequest

  class NewVmResponse = Vers::Models::NewVmResponse

  class VmAPI = Vers::Models::VmAPI

  class VmBranchByCommitParams = Vers::Models::VmBranchByCommitParams

  class VmBranchByVmParams = Vers::Models::VmBranchByVmParams

  class VmBranchParams = Vers::Models::VmBranchParams

  class VmCommitParams = Vers::Models::VmCommitParams

  class VmCommitResponse = Vers::Models::VmCommitResponse

  class VmCreateRootParams = Vers::Models::VmCreateRootParams

  class VmDeleteParams = Vers::Models::VmDeleteParams

  class VmDeleteResponse = Vers::Models::VmDeleteResponse

  class VmFromCommitRequest = Vers::Models::VmFromCommitRequest

  class VmGetSSHKeyParams = Vers::Models::VmGetSSHKeyParams

  class VmListParams = Vers::Models::VmListParams

  class VmRestoreFromCommitParams = Vers::Models::VmRestoreFromCommitParams

  class VmSSHKeyResponse = Vers::Models::VmSSHKeyResponse

  class VmStatusParams = Vers::Models::VmStatusParams

  class VmUpdateStateParams = Vers::Models::VmUpdateStateParams

  class VmUpdateStateRequest = Vers::Models::VmUpdateStateRequest
end
