module Vers
  class CommitDeleteParams = Vers::Models::CommitDeleteParams

  class CommitInfo = Vers::Models::CommitInfo

  class CommitListParams = Vers::Models::CommitListParams

  class CommitListParentsParams = Vers::Models::CommitListParentsParams

  class CommitListPublicParams = Vers::Models::CommitListPublicParams

  class CommitTagCreateParams = Vers::Models::CommitTagCreateParams

  class CommitTagDeleteParams = Vers::Models::CommitTagDeleteParams

  class CommitTagGetParams = Vers::Models::CommitTagGetParams

  class CommitTagListParams = Vers::Models::CommitTagListParams

  class CommitTagUpdateParams = Vers::Models::CommitTagUpdateParams

  class CommitUpdateParams = Vers::Models::CommitUpdateParams

  class CreateRepositoryRequest = Vers::Models::CreateRepositoryRequest

  class CreateRepositoryResponse = Vers::Models::CreateRepositoryResponse

  class CreateRepoTagRequest = Vers::Models::CreateRepoTagRequest

  class CreateRepoTagResponse = Vers::Models::CreateRepoTagResponse

  class CreateTagRequest = Vers::Models::CreateTagRequest

  class CreateTagResponse = Vers::Models::CreateTagResponse

  class ErrorResponse = Vers::Models::ErrorResponse

  class ForkRepositoryRequest = Vers::Models::ForkRepositoryRequest

  class ForkRepositoryResponse = Vers::Models::ForkRepositoryResponse

  class ListCommitsResponse = Vers::Models::ListCommitsResponse

  class ListPublicRepositoriesResponse = Vers::Models::ListPublicRepositoriesResponse

  class ListRepositoriesResponse = Vers::Models::ListRepositoriesResponse

  class ListRepoTagsResponse = Vers::Models::ListRepoTagsResponse

  class ListTagsResponse = Vers::Models::ListTagsResponse

  class NewRootRequest = Vers::Models::NewRootRequest

  class NewVmResponse = Vers::Models::NewVmResponse

  class NewVmsResponse = Vers::Models::NewVmsResponse

  class PublicRepositoryGetParams = Vers::Models::PublicRepositoryGetParams

  class PublicRepositoryGetTagParams = Vers::Models::PublicRepositoryGetTagParams

  class PublicRepositoryInfo = Vers::Models::PublicRepositoryInfo

  class PublicRepositoryListParams = Vers::Models::PublicRepositoryListParams

  class PublicRepositoryListTagsParams = Vers::Models::PublicRepositoryListTagsParams

  class RepositoryCreateParams = Vers::Models::RepositoryCreateParams

  class RepositoryCreateTagParams = Vers::Models::RepositoryCreateTagParams

  class RepositoryDeleteParams = Vers::Models::RepositoryDeleteParams

  class RepositoryDeleteTagParams = Vers::Models::RepositoryDeleteTagParams

  class RepositoryForkParams = Vers::Models::RepositoryForkParams

  class RepositoryGetParams = Vers::Models::RepositoryGetParams

  class RepositoryGetTagParams = Vers::Models::RepositoryGetTagParams

  class RepositoryInfo = Vers::Models::RepositoryInfo

  class RepositoryListParams = Vers::Models::RepositoryListParams

  class RepositoryListTagsParams = Vers::Models::RepositoryListTagsParams

  class RepositorySetVisibilityParams = Vers::Models::RepositorySetVisibilityParams

  class RepositoryUpdateTagParams = Vers::Models::RepositoryUpdateTagParams

  class RepoTagInfo = Vers::Models::RepoTagInfo

  class SetRepositoryVisibilityRequest = Vers::Models::SetRepositoryVisibilityRequest

  class TagInfo = Vers::Models::TagInfo

  class UpdateCommitRequest = Vers::Models::UpdateCommitRequest

  class UpdateRepoTagRequest = Vers::Models::UpdateRepoTagRequest

  class UpdateTagRequest = Vers::Models::UpdateTagRequest

  class VmAPI = Vers::Models::VmAPI

  class VmBranchByCommitParams = Vers::Models::VmBranchByCommitParams

  class VmBranchByTagParams = Vers::Models::VmBranchByTagParams

  class VmBranchByVmParams = Vers::Models::VmBranchByVmParams

  class VmBranchParams = Vers::Models::VmBranchParams

  class VmCommitParams = Vers::Models::VmCommitParams

  class VmCommitResponse = Vers::Models::VmCommitResponse

  class VmCreateRootParams = Vers::Models::VmCreateRootParams

  class VmDeleteParams = Vers::Models::VmDeleteParams

  class VmDeleteResponse = Vers::Models::VmDeleteResponse

  module VmFromCommitRequest = Vers::Models::VmFromCommitRequest

  class VmGetMetadataParams = Vers::Models::VmGetMetadataParams

  class VmGetSSHKeyParams = Vers::Models::VmGetSSHKeyParams

  class VmListParams = Vers::Models::VmListParams

  class VmMetadataResponse = Vers::Models::VmMetadataResponse

  class VmResizeDiskParams = Vers::Models::VmResizeDiskParams

  class VmResizeDiskRequest = Vers::Models::VmResizeDiskRequest

  class VmRestoreFromCommitParams = Vers::Models::VmRestoreFromCommitParams

  class VmSSHKeyResponse = Vers::Models::VmSSHKeyResponse

  class VmStatusParams = Vers::Models::VmStatusParams

  class VmUpdateStateParams = Vers::Models::VmUpdateStateParams

  class VmUpdateStateRequest = Vers::Models::VmUpdateStateRequest
end
