module Vers
  module Resources
    class Orchestrator
      attr_reader vm: Vers::Resources::Orchestrator::Vm

      attr_reader node: Vers::Resources::Orchestrator::Node

      def initialize: (client: Vers::Client) -> void
    end
  end
end
